"""Add current timestamp

Revision ID: 12f345dc99b7
Revises: 91b72d57f082
Create Date: 2025-05-19 17:03:14.713753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f345dc99b7'
down_revision: Union[str, None] = '91b72d57f082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_column('jobs', 'created_at')
    # ### end Alembic commands ###
