"""Remove id_deleted column

Revision ID: ce58fd986814
Revises: bdfaaa64444c
Create Date: 2025-05-13 13:30:06.581172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce58fd986814'
down_revision: Union[str, None] = 'bdfaaa64444c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
