"""Add new columns is_deleted and is_blocked

Revision ID: fe2c76b80b3b
Revises: 40fa83fcd2db
Create Date: 2025-05-13 13:41:37.144145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2c76b80b3b'
down_revision: Union[str, None] = '40fa83fcd2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
